#!/bin/bash

# sed -i has extra param in OSX
SEDBAK=""

UNAME_OUT="$(uname -s)"
case "${UNAME_OUT}" in
    Linux*)     MACHINE=Linux;;
    Darwin*)    MACHINE=Mac
                SEDBAK=".bak"
                ;;
    CYGWIN*)    MACHINE=Cygwin;;
    MINGW*)     MACHINE=MinGw;;
    *)          MACHINE="UNKNOWN:${UNAME_OUT}"
esac
#echo OS is ${MACHINE}

CWD=`pwd`
HERE=`echo $CWD | sed 's/\//\\\\\//g'`\\/kubecfg
SUBDOMAIN=`grep name_prefix ../hosts | awk -F "=" '{print $2}'`
ECS1_IP=`host ecs1.$SUBDOMAIN.cloudera-field.net|awk '{print $4}'`

cp kubecfg/admin-kubeconfig.yaml kubecfg/admin.yaml

#sed -i $SEDBAK "s/127.0.0.1/ecs1.myecs.cloudera-field.net/" kubecfg/admin.yaml
sed -i $SEDBAK "s/127.0.0.1/kubernetes.default.svc.cluster.local/" kubecfg/admin.yaml
sed -i $SEDBAK "s/server-ca.crt/rancher-server-ca.crt/" kubecfg/admin.yaml
sed -i $SEDBAK "s/\/var\/lib\/rancher\/rke2\/server\/tls/$HERE/" kubecfg/admin.yaml
sed -i $SEDBAK "s/\/var\/lib\/rancher\/rke2\/server\/tls/$HERE/" kubecfg/admin.yaml

echo Local hosts entry:
echo $ECS1_IP  kubernetes.default.svc.cluster.local
echo "export KUBECONFIG=$CWD/kubecfg/admin.yaml"
rm kubecfg/*.bak
